[package]
name = "cargo-rr"
version = "0.1.0"
authors = ["Daniel Franklin <daniel@danielzfranklin.org>"]
edition = "2018"
description = "A light wrapper around the time-travelling debugger rr"
license = "MIT"
keywords = ["rr", "debug", "debugger", "test"]
categories = ["development-tools"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
structopt = "0.3.21"
anyhow = "1.0.40"
clap = "2.33.3"
cargo_metadata = "0.13.1"
dialoguer = "0.8.0"
camino = "1.0.4"
ctrlc = "3.1.9"
